#!/usr/bin/env bash

# MIT License
#
# Copyright © 2020 Darren Mo.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ "$#" -ne 0 ]; then
   echo "Usage: \"$0\"" 1>&2
   exit 2
fi

SCRIPT_DIR="$(dirname "$BASH_SOURCE")"
cd "$SCRIPT_DIR"

BOLD_TEXT=$(tput bold)
RESET_TEXT=$(tput sgr0)
print-status() {
   echo "$BOLD_TEXT$1$RESET_TEXT" 1>&2
}

cd "Sources/DMPreferencesWindow" \
   || exit 1

STRING_TABLES_DIR="Resources/en.lproj/"

print-status "Generating string tables into \`$PWD/$STRING_TABLES_DIR\`..."
find . -name "*.swift" -print0 | xargs -0 \
   genstrings -o "$STRING_TABLES_DIR" \
      || exit 1
print-status "Done generating string tables."
